
CREATE  TABLE USERS (
ID INT PRIMARY KEY  IDENTITY(1,1),
[NAME] VARCHAR(60) NOT NULL,
PASSWORD CHAR(9) NOT NULL,
 
NUMBER CHAR(9) UNIQUE NOT NULL,

CREATEDDATE  DATETIME DEFAULT GETDATE()

);




CREATE TABLE BUNDLES (
ID INT PRIMARY KEY IDENTITY (1,1),
[NAME] VARCHAR (100) NOT NULL,
SPEED VARCHAR (50) NOT NULL,
PRICE  DECIMAL (10,2) NOT NULL ,
DURATION_DAYS INT NOT NULL,

CREATEDDATE  DATETIME DEFAULT GETDATE()
);

  CREATE TABLE OFFERS (
  ID INT PRIMARY KEY IDENTITY(1,1),
  [NAME] VARCHAR(50) NOT NULL,
  DISCOUNT  DECIMAL (5,2) DEFAULT 0,
  SPEED VARCHAR (50) NOT NULL,
PRICE  DECIMAL (10,2) NOT NULL ,
DURATION_DAYS INT NOT NULL,

  CREATEDDATE  DATETIME DEFAULT GETDATE()
  );
  CREATE TABLE TRANSACTIONS(
ID INT PRIMARY KEY  IDENTITY(1,1),
TRANSACTIONDATE DATETIME DEFAULT GETDATE(),
AMOUNT DECIMAL (10,2) NOT NULL ,
 PHONE CHAR(9) NOT NULL,
 FINALPRICE DECIMAL (10,2),
 USERID INT  FOREIGN KEY REFERENCES USERS(ID),
 BUNDLESID INT FOREIGN KEY REFERENCES BUNDLES(ID) ,
 STATUS  VARCHAR(20) DEFAULT 'ACTIVE' ,

CREATEDDATE  DATETIME DEFAULT GETDATE()
);
  

